### PR TITLE
Add ES5 compiled dist

### PR DESCRIPTION
**Pull request by mturco**
This adds an ES5-compiled version in `dist/` and switches `index.js` to require it instead. Allows this package to be imported as is by bundlers like Webpack. Forked for my own usage but figured I'd share in case you were interested.

Related: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

### CODE REVIEW

**Comment by JHotterbeekx** [comment]
I always was under the assumption that webpack would build the npm packages as wellI. It seems really weird that I control the transpiling result while people using this in their projecet might want to transpile into ES2015, or even lower, which makes the ES5 in the distribution useless. Are you sure this isn't a limitation of react-create-app? I've created a test project to try my package out and it seems to transpile to ES5 just fine.

**Comment by mturco** [comment]
I think you're right. Webpack 2+ supposedly does automatically transpile dependencies. Not sure why it wasn't working for me but it could be something wrong with my config. Feel free to close this!

**Comment by JHotterbeekxBannerconnect** [comment]
No worries, thanks for taking the time to post your findings and thanks for using the the package :)
I'm closing the issue now, but please don't hesitate to open one again should you need some support.

**Comment by JHotterbeekx** [comment]
No worries, thanks for taking the time to post your findings and thanks for using the the package :)
I'm closing the issue now, but please don't hesitate to open one again should you need some support.

**Pull request closed without merging**
